# Generated by Django 6.0.3 on 2026-04-17 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="workerprofile",
            name="is_online",
            field=models.BooleanField(
                default=True, help_text="Toggle to show/hide in client searches"
            ),
        ),
    ]
