# Generated by Django 6.0.3 on 2026-04-17 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_workerprofile_is_online"),
    ]

    operations = [
        migrations.CreateModel(
            name="QuickTapTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="review",
            name="quick_tap_tag",
        ),
        migrations.AddField(
            model_name="review",
            name="comment",
            field=models.TextField(
                blank=True, help_text="Optional comment from the client"
            ),
        ),
        migrations.AlterField(
            model_name="workerprofile",
            name="location",
            field=models.CharField(
                choices=[
                    ("Kandy", "Kandy"),
                    ("Colombo", "Colombo"),
                    ("Galle", "Galle"),
                    ("Jaffna", "Jaffna"),
                    ("Anuradhapura", "Anuradhapura"),
                    ("Trincomalee", "Trincomalee"),
                    ("Matara", "Matara"),
                    ("Hambantota", "Hambantota"),
                    ("Nuwara Eliya", "Nuwara Eliya"),
                    ("Badulla", "Badulla"),
                    ("Ratnapura", "Ratnapura"),
                    ("Puttalam", "Puttalam"),
                    ("Kurunegala", "Kurunegala"),
                    ("Monaragala", "Monaragala"),
                    ("Vavuniya", "Vavuniya"),
                    ("Mannar", "Mannar"),
                    ("Kilinochchi", "Kilinochchi"),
                    ("Mullaitivu", "Mullaitivu"),
                ],
                help_text="Primary location of work",
                max_length=255,
            ),
        ),
        migrations.CreateModel(
            name="ReviewQUickTapTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quick_tap_tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review_tags",
                        to="core.quicktaptag",
                    ),
                ),
                (
                    "review",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quick_tap_tags",
                        to="core.review",
                    ),
                ),
            ],
        ),
    ]
