# Generated by Django 6.0.3 on 2026-04-17 08:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_quicktaptag_remove_review_quick_tap_tag_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="quicktap_tags",
            field=models.ManyToManyField(
                blank=True,
                help_text="Select applicable quick tap tags",
                to="core.quicktaptag",
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="client_name",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews_given",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.DeleteModel(
            name="ReviewQUickTapTag",
        ),
    ]
