# Generated by Django 6.0.3 on 2026-04-17 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="is_client",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="is_worker",
        ),
        migrations.AddField(
            model_name="customuser",
            name="active_role",
            field=models.CharField(
                choices=[("Client", "Client"), ("Worker", "Worker")],
                default="Client",
                max_length=10,
            ),
        ),
    ]
