# Generated by Django 6.0.3 on 2026-04-17 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_remove_customuser_is_client_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="full_name",
            field=models.CharField(default="john doe", max_length=255),
        ),
    ]
